[platformio]
default_envs = pico-portal-auto
build_dir = ${sysenv.USERPROFILE}/.platformio/build/rp2040-usb-ethernet-portal

[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#develop
framework = picosdk
upload_protocol = picoprobe
debug_tool = picoprobe
debug_speed = 5000
build_flags =
    -DPIO_STDIO_UART
    -DCFG_TUSB_CONFIG_FILE=\"tusb_config.h\"
extra_scripts =
    pre:scripts/extra_picosdk_sources.py

[env:pico-portal-auto]
board = pico
build_flags =
    ${env.build_flags}
    -DCONTROL_GPIO=25u
    -DUSB_NET_MODE_ECM_FIRST=1
    -DUSB_NET_GLOBAL_MAC=1
    -DUSB_NET_ADVERTISE_GATEWAY=1
    -DUSB_NET_CROSS_PLATFORM=1

[env:pico-portal-android]
board = pico
build_flags =
    ${env.build_flags}
    -DCONTROL_GPIO=25u
    -DUSB_NET_MODE_ECM_ONLY=1
    -DUSB_NET_GLOBAL_MAC=1
    -DUSB_NET_ADVERTISE_GATEWAY=1

[env:pico-portal-windows]
board = pico
build_flags =
    ${env.build_flags}
    -DCONTROL_GPIO=25u
    -DUSB_NET_MODE_NCM=1
    -DUSB_NET_GLOBAL_MAC=1
    -DUSB_NET_ADVERTISE_GATEWAY=1

[env:pico-portal-windows-rndis]
board = pico
build_flags =
    ${env.build_flags}
    -DCONTROL_GPIO=25u
    -DUSB_NET_GLOBAL_MAC=1
    -DUSB_NET_ADVERTISE_GATEWAY=1

[env:kb2040-portal-auto]
board = adafruit_kb2040
build_flags =
    ${env.build_flags}
    -DCONTROL_GPIO=10u
    -DUSB_NET_MODE_ECM_FIRST=1
    -DUSB_NET_GLOBAL_MAC=1
    -DUSB_NET_ADVERTISE_GATEWAY=1
    -DUSB_NET_CROSS_PLATFORM=1

[env:kb2040-portal-android]
board = adafruit_kb2040
build_flags =
    ${env.build_flags}
    -DCONTROL_GPIO=10u
    -DUSB_NET_MODE_ECM_ONLY=1
    -DUSB_NET_GLOBAL_MAC=1
    -DUSB_NET_ADVERTISE_GATEWAY=1

[env:kb2040-portal-windows]
board = adafruit_kb2040
build_flags =
    ${env.build_flags}
    -DCONTROL_GPIO=10u
    -DUSB_NET_MODE_NCM=1
    -DUSB_NET_GLOBAL_MAC=1
    -DUSB_NET_ADVERTISE_GATEWAY=1

[env:kb2040-portal-windows-rndis]
board = adafruit_kb2040
build_flags =
    ${env.build_flags}
    -DCONTROL_GPIO=10u
    -DUSB_NET_GLOBAL_MAC=1
    -DUSB_NET_ADVERTISE_GATEWAY=1

[env:kb2040-bootsel]
board = adafruit_kb2040
upload_protocol = picotool
build_flags =
    ${env.build_flags}
    -DCONTROL_GPIO=10u
