#pragma once

#include "rp2040_usb_ethernet_portal_config.h"

#define NO_SYS 1
#define LWIP_SOCKET 0
#define LWIP_NETCONN 0
#define SYS_LIGHTWEIGHT_PROT 0

#define LWIP_IPV4 1
#define LWIP_IPV6 0
#define LWIP_ICMP 1
#define LWIP_TCP 1
#define LWIP_UDP 1
#define LWIP_DHCP 0
#define LWIP_DNS 0
#define LWIP_IP_ACCEPT_UDP_PORT(p) ((p) == PP_NTOHS(67))

#define LWIP_ARP 1
#define LWIP_ETHERNET 1
#define LWIP_RAW 1
#define LWIP_NETIF_LINK_CALLBACK 1

#define MEM_ALIGNMENT 4
#define MEM_SIZE RP2040_USB_PORTAL_LWIP_MEM_SIZE
#define MEMP_NUM_PBUF RP2040_USB_PORTAL_LWIP_MEMP_NUM_PBUF
#define MEMP_NUM_UDP_PCB RP2040_USB_PORTAL_LWIP_MEMP_NUM_UDP_PCB
#define MEMP_NUM_TCP_PCB RP2040_USB_PORTAL_LWIP_MEMP_NUM_TCP_PCB
#define MEMP_NUM_TCP_SEG RP2040_USB_PORTAL_LWIP_MEMP_NUM_TCP_SEG
#define PBUF_POOL_SIZE RP2040_USB_PORTAL_LWIP_PBUF_POOL_SIZE
#define PBUF_POOL_BUFSIZE RP2040_USB_PORTAL_LWIP_PBUF_POOL_BUFSIZE
#define TCP_MSS RP2040_USB_PORTAL_LWIP_TCP_MSS
#define TCP_SND_BUF (RP2040_USB_PORTAL_LWIP_TCP_SND_BUF_MULTIPLIER * TCP_MSS)
#define TCP_WND (RP2040_USB_PORTAL_LWIP_TCP_WND_MULTIPLIER * TCP_MSS)

#define LWIP_TIMEVAL_PRIVATE 0
#define LWIP_NO_CTYPE_H 0
#define LWIP_STATS 0
#define LWIP_SINGLE_NETIF 1
