#pragma once

/* Captive portal network defaults. Override these in build flags or before
 * including the library header if a project needs a different subnet. */
#ifndef RP2040_USB_PORTAL_IP_A
#define RP2040_USB_PORTAL_IP_A 192
#endif
#ifndef RP2040_USB_PORTAL_IP_B
#define RP2040_USB_PORTAL_IP_B 168
#endif
#ifndef RP2040_USB_PORTAL_IP_C
#define RP2040_USB_PORTAL_IP_C 4
#endif
#ifndef RP2040_USB_PORTAL_IP_D
#define RP2040_USB_PORTAL_IP_D 1
#endif

#ifndef RP2040_USB_PORTAL_NETMASK_A
#define RP2040_USB_PORTAL_NETMASK_A 255
#endif
#ifndef RP2040_USB_PORTAL_NETMASK_B
#define RP2040_USB_PORTAL_NETMASK_B 255
#endif
#ifndef RP2040_USB_PORTAL_NETMASK_C
#define RP2040_USB_PORTAL_NETMASK_C 255
#endif
#ifndef RP2040_USB_PORTAL_NETMASK_D
#define RP2040_USB_PORTAL_NETMASK_D 0
#endif

#ifndef RP2040_USB_PORTAL_GATEWAY_A
#define RP2040_USB_PORTAL_GATEWAY_A 0
#endif
#ifndef RP2040_USB_PORTAL_GATEWAY_B
#define RP2040_USB_PORTAL_GATEWAY_B 0
#endif
#ifndef RP2040_USB_PORTAL_GATEWAY_C
#define RP2040_USB_PORTAL_GATEWAY_C 0
#endif
#ifndef RP2040_USB_PORTAL_GATEWAY_D
#define RP2040_USB_PORTAL_GATEWAY_D 0
#endif

#ifndef RP2040_USB_PORTAL_DHCP_START_A
#define RP2040_USB_PORTAL_DHCP_START_A RP2040_USB_PORTAL_IP_A
#endif
#ifndef RP2040_USB_PORTAL_DHCP_START_B
#define RP2040_USB_PORTAL_DHCP_START_B RP2040_USB_PORTAL_IP_B
#endif
#ifndef RP2040_USB_PORTAL_DHCP_START_C
#define RP2040_USB_PORTAL_DHCP_START_C RP2040_USB_PORTAL_IP_C
#endif
#ifndef RP2040_USB_PORTAL_DHCP_START_D
#define RP2040_USB_PORTAL_DHCP_START_D 2
#endif

#ifndef RP2040_USB_PORTAL_DHCP_LEASE_COUNT
#define RP2040_USB_PORTAL_DHCP_LEASE_COUNT 3
#endif
#ifndef RP2040_USB_PORTAL_DHCP_LEASE_SECONDS
#define RP2040_USB_PORTAL_DHCP_LEASE_SECONDS (24u * 60u * 60u)
#endif
#ifndef RP2040_USB_PORTAL_DHCP_PORT
#define RP2040_USB_PORTAL_DHCP_PORT 67
#endif
#ifndef RP2040_USB_PORTAL_DNS_PORT
#define RP2040_USB_PORTAL_DNS_PORT 53
#endif
#ifndef RP2040_USB_PORTAL_DHCP_DOMAIN
#define RP2040_USB_PORTAL_DHCP_DOMAIN "rp2040.local"
#endif

/* Android behaved best in testing when DHCP advertised the device as router
 * and DNS, even though the link is only for local portal access. */
#ifndef RP2040_USB_PORTAL_ADVERTISE_GATEWAY
#define RP2040_USB_PORTAL_ADVERTISE_GATEWAY 1
#endif

#ifndef RP2040_USB_PORTAL_DNS_A
#define RP2040_USB_PORTAL_DNS_A RP2040_USB_PORTAL_IP_A
#endif
#ifndef RP2040_USB_PORTAL_DNS_B
#define RP2040_USB_PORTAL_DNS_B RP2040_USB_PORTAL_IP_B
#endif
#ifndef RP2040_USB_PORTAL_DNS_C
#define RP2040_USB_PORTAL_DNS_C RP2040_USB_PORTAL_IP_C
#endif
#ifndef RP2040_USB_PORTAL_DNS_D
#define RP2040_USB_PORTAL_DNS_D RP2040_USB_PORTAL_IP_D
#endif

#ifndef RP2040_USB_PORTAL_ROUTER_A
#define RP2040_USB_PORTAL_ROUTER_A RP2040_USB_PORTAL_IP_A
#endif
#ifndef RP2040_USB_PORTAL_ROUTER_B
#define RP2040_USB_PORTAL_ROUTER_B RP2040_USB_PORTAL_IP_B
#endif
#ifndef RP2040_USB_PORTAL_ROUTER_C
#define RP2040_USB_PORTAL_ROUTER_C RP2040_USB_PORTAL_IP_C
#endif
#ifndef RP2040_USB_PORTAL_ROUTER_D
#define RP2040_USB_PORTAL_ROUTER_D RP2040_USB_PORTAL_IP_D
#endif

#ifndef RP2040_USB_PORTAL_GLOBAL_MAC
#define RP2040_USB_PORTAL_GLOBAL_MAC 1
#endif

/* Define RP2040_USB_PORTAL_DEFAULT_REDIRECT_URL only when a project needs a
 * literal redirect target. By default the library derives http://<address>/
 * from RP2040_USB_PORTAL_IP_* or the runtime config address. */

/* LwIP raw-API defaults used by the portal. Projects with heavier TCP/UDP
 * workloads can raise these without editing lwipopts.h. */
#ifndef RP2040_USB_PORTAL_LWIP_MEM_SIZE
#define RP2040_USB_PORTAL_LWIP_MEM_SIZE (16 * 1024)
#endif
#ifndef RP2040_USB_PORTAL_LWIP_MEMP_NUM_PBUF
#define RP2040_USB_PORTAL_LWIP_MEMP_NUM_PBUF 32
#endif
#ifndef RP2040_USB_PORTAL_LWIP_MEMP_NUM_UDP_PCB
#define RP2040_USB_PORTAL_LWIP_MEMP_NUM_UDP_PCB 8
#endif
#ifndef RP2040_USB_PORTAL_LWIP_MEMP_NUM_TCP_PCB
#define RP2040_USB_PORTAL_LWIP_MEMP_NUM_TCP_PCB 16
#endif
#ifndef RP2040_USB_PORTAL_LWIP_MEMP_NUM_TCP_SEG
#define RP2040_USB_PORTAL_LWIP_MEMP_NUM_TCP_SEG 32
#endif
#ifndef RP2040_USB_PORTAL_LWIP_PBUF_POOL_SIZE
#define RP2040_USB_PORTAL_LWIP_PBUF_POOL_SIZE 24
#endif
#ifndef RP2040_USB_PORTAL_LWIP_PBUF_POOL_BUFSIZE
#define RP2040_USB_PORTAL_LWIP_PBUF_POOL_BUFSIZE 1536
#endif
#ifndef RP2040_USB_PORTAL_LWIP_TCP_MSS
#define RP2040_USB_PORTAL_LWIP_TCP_MSS 1460
#endif
#ifndef RP2040_USB_PORTAL_LWIP_TCP_SND_BUF_MULTIPLIER
#define RP2040_USB_PORTAL_LWIP_TCP_SND_BUF_MULTIPLIER 4
#endif
#ifndef RP2040_USB_PORTAL_LWIP_TCP_WND_MULTIPLIER
#define RP2040_USB_PORTAL_LWIP_TCP_WND_MULTIPLIER 4
#endif
