#pragma once

#include "lwipopts.h"
#include "tusb_option.h"

#define CFG_TUD_ENABLED 1
#define CFG_TUH_ENABLED 0
#define CFG_TUSB_RHPORT0_MODE (OPT_MODE_DEVICE | OPT_MODE_FULL_SPEED)
#define CFG_TUD_MAX_SPEED OPT_MODE_FULL_SPEED
#define CFG_TUD_ENDPOINT0_SIZE 64

#define CFG_TUSB_MEM_SECTION
#define CFG_TUSB_MEM_ALIGN __attribute__((aligned(4)))

#ifndef USB_PORTAL_ENABLE_CDC_SERIAL
#define USB_PORTAL_ENABLE_CDC_SERIAL 1
#endif

#if USB_PORTAL_ENABLE_CDC_SERIAL
#define CFG_TUD_CDC 1
#else
#define CFG_TUD_CDC 0
#endif

#define CFG_TUD_MSC 0
#define CFG_TUD_HID 0
#define CFG_TUD_MIDI 0
#define CFG_TUD_VENDOR 0

#define CFG_TUD_CDC_RX_BUFSIZE 256
#define CFG_TUD_CDC_TX_BUFSIZE 256
#define CFG_TUD_CDC_EP_BUFSIZE 64

#ifndef USB_NET_MODE_NCM
#define USB_NET_MODE_NCM 0
#endif
#ifndef USB_NET_MODE_ECM_FIRST
#define USB_NET_MODE_ECM_FIRST 0
#endif
#ifndef USB_NET_MODE_ECM_ONLY
#define USB_NET_MODE_ECM_ONLY 0
#endif
#ifndef USB_NET_CROSS_PLATFORM
#define USB_NET_CROSS_PLATFORM 0
#endif

#if USB_NET_MODE_NCM
#define CFG_TUD_ECM_RNDIS 0
#define CFG_TUD_NCM 1
#elif USB_NET_MODE_ECM_FIRST || USB_NET_MODE_ECM_ONLY
#define CFG_TUD_ECM_RNDIS 1
#define CFG_TUD_NCM 0
#else
#define CFG_TUD_ECM_RNDIS 1
#define CFG_TUD_NCM 0
#endif

#define CFG_TUD_NET_MTU 1514

#define CFG_TUD_NCM_IN_NTB_MAX_SIZE (2 * TCP_MSS + 100)
#define CFG_TUD_NCM_OUT_NTB_MAX_SIZE (2 * TCP_MSS + 100)
#define CFG_TUD_NCM_IN_NTB_N 1
#define CFG_TUD_NCM_OUT_NTB_N 1
